### ISSUE TITLE
Setting Limits & Requests on an Application section breaks microsweeper application

### ISSUE THREAD

**Issue by augustrh** [rhpds/bookbag-aro-mobb#10]
Running the labs in order I saw the following:
I deployed microsweeper and it worked fine. All subsequent labs worked.
Got to the "Setting Limits & Requests on an Application" and observed:

```
[azure@bastion-kkcsf ~]$ oc get pods -n microsweeper-ex
NAME                                       READY   STATUS      RESTARTS   AGE
microsweeper-appservice-1-build            0/1     Completed   0          13m
microsweeper-appservice-664b4fdc48-5xmgb   1/1     Running     0          11m
```

Then ran the following command and saw the output:

```
[azure@bastion-kkcsf ~]$ oc -n microsweeper-ex set resources deployment/microsweeper-appservice \
>    --limits=cpu=60m,memory=250Mi \
>    --requests=cpu=50m,memory=200Mi
Warning: would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "microsweeper-ap
pservice" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "microsweep
er-appservice" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "microswe
eper-appservice" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "microsweeper-appserv
ice" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
deployment.apps/microsweeper-appservice resource requirements updated
```

Observed microsweeper

```
[azure@bastion-kkcsf ~]$ oc get pods -n microsweeper-ex
NAME                                       READY   STATUS              RESTARTS   AGE
microsweeper-appservice-1-build            0/1     Completed           0          14m
microsweeper-appservice-576fb9ffbd-r8rg2   0/1     ContainerCreating   0          4s
microsweeper-appservice-664b4fdc48-5xmgb   1/1     Running             0          12m
```

Continued to monitor:

```
[azure@bastion-kkcsf ~]$ oc get pods -n microsweeper-ex
NAME                                       READY   STATUS      RESTARTS   AGE
microsweeper-appservice-1-build            0/1     Completed   0          14m
microsweeper-appservice-576fb9ffbd-r8rg2   1/1     Running     0          9s
[azure@bastion-kkcsf ~]$ oc get pods -n microsweeper-ex
NAME                                       READY   STATUS      RESTARTS   AGE
microsweeper-appservice-1-build            0/1     Completed   0          14m
microsweeper-appservice-576fb9ffbd-r8rg2   1/1     Running     0          21s
[azure@bastion-kkcsf ~]$ oc get pods -n microsweeper-ex
NAME                                       READY   STATUS      RESTARTS   AGE
microsweeper-appservice-1-build            0/1     Completed   0          15m
microsweeper-appservice-576fb9ffbd-r8rg2   1/1     Running     0          44s
[azure@bastion-kkcsf ~]$ oc get pods -n microsweeper-ex
NAME                                       READY   STATUS      RESTARTS      AGE
microsweeper-appservice-1-build            0/1     Completed   0             16m
microsweeper-appservice-576fb9ffbd-r8rg2   1/1     Running     1 (13s ago)   2m1s
[azure@bastion-kkcsf ~]$ oc get pods -n microsweeper-ex --watch
NAME                                       READY   STATUS      RESTARTS      AGE
microsweeper-appservice-1-build            0/1     Completed   0             16m
microsweeper-appservice-576fb9ffbd-r8rg2   1/1     Running     1 (19s ago)   2m7s
^C[azure@bastion-kkcsf ~]$ oc get pods -n microsweeper-ex
NAME                                       READY   STATUS      RESTARTS      AGE
microsweeper-appservice-1-build            0/1     Completed   0             17m
microsweeper-appservice-576fb9ffbd-r8rg2   1/1     Running     1 (77s ago)   3m5s
[azure@bastion-kkcsf ~]$ oc get pods -n microsweeper-ex --watch
NAME                                       READY   STATUS      RESTARTS      AGE
microsweeper-appservice-1-build            0/1     Completed   0             17m
microsweeper-appservice-576fb9ffbd-r8rg2   1/1     Running     1 (93s ago)   3m21s
microsweeper-appservice-576fb9ffbd-r8rg2   0/1     Error       1 (107s ago)   3m35s
microsweeper-appservice-576fb9ffbd-r8rg2   0/1     CrashLoopBackOff   1 (14s ago)    3m48s
microsweeper-appservice-576fb9ffbd-r8rg2   1/1     Running            2 (16s ago)    3m50s

```

And pod is now unstable.

Looking at pod logs I see:

```
exec java -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/quarkus-run.jar
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2023-12-06 08:09:59,882 WARN  [io.qua.net.run.NettyRecorder] (Thread-0) Netty DefaultChannelId initialization (with io.netty.machineId system property set to a1:85:ae:66:2f:62:13:09) took more than a second
2023-12-06 08:10:28,280 WARN  [org.hib.eng.jdb.env.int.JdbcEnvironmentInitiator] (JPA Startup Thread: <default>) HHH000342: Could not obtain connection to query metadata: java.sql.SQLException: Acquisition timeout while waiting for new connection
	at io.agroal.pool.ConnectionPool.handlerFromSharedCache(ConnectionPool.java:320)
	at io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:248)
	at io.agroal.pool.DataSource.getConnection(DataSource.java:86)
	at io.quarkus.hibernate.orm.runtime.customized.QuarkusConnectionProvider.getConnection(QuarkusConnectionProvider.java:23)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:181)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:68)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:237)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:51)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:107)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:246)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
	at org.hibernate.boot.internal.SessionFactoryOptionsBuilder.<init>(SessionFactoryOptionsBuilder.java:272)
	at io.quarkus.hibernate.orm.runtime.recording.PrevalidatedQuarkusMetadata.buildSessionFactoryOptionsBuilder(PrevalidatedQuarkusMetadata.java:68)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:72)
	at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:71)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:138)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:54)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at io.agroal.pool.ConnectionPool.handlerFromSharedCache(ConnectionPool.java:296)
	... 23 more

2023-12-06 08:10:34,580 WARN  [io.agr.pool] (agroal-11) Datasource '<default>': SSL error: Connection reset by peer (Write failed)
2023-12-06 08:10:45,785 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (JPA Startup Thread: <default>) SQL Error: 0, SQLState: null
2023-12-06 08:10:45,785 ERROR [org.hib.eng.jdb.spi.SqlExceptionHelper] (JPA Startup Thread: <default>) Acquisition timeout while waiting for new connection
2023-12-06 08:10:49,280 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at io.agroal.pool.ConnectionPool.handlerFromSharedCache(ConnectionPool.java:296)
	at io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:248)
	at io.agroal.pool.DataSource.getConnection(DataSource.java:86)
	at io.quarkus.hibernate.orm.runtime.customized.QuarkusConnectionProvider.getConnection(QuarkusConnectionProvider.java:23)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:181)
	at org.hibernate.resource.transaction.backend.jta.internal.DdlTransactionIsolatorJtaImpl.<init>(DdlTransactionIsolatorJtaImpl.java:59)
	at org.hibernate.resource.transaction.backend.jta.internal.JtaTransactionCoordinatorBuilderImpl.buildDdlTransactionIsolator(JtaTransactionCoordinatorBuilderImpl.java:53)
	at org.hibernate.tool.schema.internal.HibernateSchemaManagementTool.getDdlTransactionIsolator(HibernateSchemaManagementTool.java:205)
	at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.doMigration(AbstractSchemaMigrator.java:102)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:196)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:85)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:335)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:74)
	at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:71)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:138)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:54)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

And the app is down with the 

Application is not available
The application is currently not serving requests at this endpoint. It may not have been started or is still starting.

Error on the route.

Left it running and came back an hour later and 

```
NAME                                       READY   STATUS             RESTARTS       AGE
microsweeper-appservice-1-build            0/1     Completed          0              88m
microsweeper-appservice-576fb9ffbd-r8rg2   0/1     CrashLoopBackOff   14 (55s ago)   74m
microsweeper-appservice-576fb9ffbd-r8rg2   1/1     Running            15 (5m10s ago)   78m 
```

**Comment by augustrh** [comment]
Testing more on this but raising in case it's known or known fix.

**Comment by augustrh** [comment]
I'll let this run for 24hours and if ok send PR

**Comment by wkulhanek** [comment]
PR merged. Thanks @augustrh
